Update unredactor.tsv
cegme/cs5293sp22 pull request #46
Opened 2022-05-05 19:14 UTC by raj768

2022-05-05 23:43 UTC, cegme requested changes
Please add more context words.
Pull the latest and re-request the review.

2022-05-05 23:43 UTC, cegme commented on unredactor.tsv
> +raj768  test  David Norwell  █████████████, suddenly gets a yen for adoption.
test -> testing

2022-05-05 23:43 UTC, cegme commented on unredactor.tsv
> +raj768  training  Kevin  █████ gave convincing performances.
Is this tab-separated?

2022-05-06 01:10 UTC, raj768 commented on unredactor.tsv
> +raj768  training  Kevin  █████ gave convincing performances.
Yeah.. I think so

2022-05-07 02:01 UTC, cegme commented on unredactor.tsv
> +raj768  training  Kevin  █████ gave convincing performances.
@raj768 go ahead and re-request a review

2022-05-07 03:45 UTC, closed without merging