providing training datas
cegme/cs5293sp22 pull request #54
Opened 2022-05-06 02:43 UTC by mat-crick

2022-05-06 02:55 UTC, cegme requested changes
Almost there. Fix small changes. re-request a review

2022-05-06 02:55 UTC, cegme commented on unredactor.tsv
> +mat-crick   Validation	Vincent Price     █████████████ must have taped his contribution in a single morning and probably didn't remember it a week later
Validation needs to be lowercase

2022-05-06 03:33 UTC, mat-crick commented on unredactor.tsv
> +mat-crick   Validation	Vincent Price     █████████████ must have taped his contribution in a single morning and probably didn't remember it a week later
changed into lowercase

2022-05-06 23:03 UTC, mat-crick reviewed
updated

2022-05-07 02:00 UTC, cegme commented
@mat-crick Go ahead and re-request a review with the latest changes from other students pulled and merged

2022-05-07 20:50 UTC, closed without merging