Update unredactor.tsv
cegme/cs5293sp22 pull request #63
Opened 2022-05-06 19:26 UTC by pinn0002

add sentences to latest version from upstream

2022-05-07 01:18 UTC, cegme requested changes
Pleaes quality control reviews. Also remove the <br /> if possible. Re-request the submission

2022-05-07 01:18 UTC, cegme commented on unredactor.tsv
> +pinn0002	training	Nuff	████ Said.<br /><br />These Lines are Just Filler.
Not a name

2022-05-07 01:18 UTC, cegme commented on unredactor.tsv
> +pinn0002	validation	Might	█████ as well jack into someone else's imagination, and pretend to be doing something interesting.
Not a name

2022-05-07 01:18 UTC, cegme commented on unredactor.tsv
> +pinn0002	training	Preminger	█████████ may have been aiming for a dream effect, as the cardboard backgrounds give the proceedings the surreal feeling of a nightmare operetta, perhaps harking back to █
Two redactions

2022-05-07 01:24 UTC, pinn0002 commented on unredactor.tsv
> +pinn0002	training	Preminger	█████████ may have been aiming for a dream effect, as the cardboard backgrounds give the proceedings the surreal feeling of a nightmare operetta, perhaps harking back to █
Preminger has repeated twice. Should I delete the sentence then?

2022-05-07 01:54 UTC, cegme commented on unredactor.tsv
> +pinn0002	training	Preminger	█████████ may have been aiming for a dream effect, as the cardboard backgrounds give the proceedings the surreal feeling of a nightmare operetta, perhaps harking back to █
You can erase it or keep one of them.

2022-05-07 02:00 UTC, pinn0002 commented on unredactor.tsv
> +pinn0002	training	Preminger	█████████ may have been aiming for a dream effect, as the cardboard backgrounds give the proceedings the surreal feeling of a nightmare operetta, perhaps harking back to █
Thanks Professor, I have added new sentence instead. But could you please let me  know if I have to create new pull request on the latest changes?

2022-05-07 02:04 UTC, cegme commented on unredactor.tsv
> +pinn0002	training	Preminger	█████████ may have been aiming for a dream effect, as the cardboard backgrounds give the proceedings the surreal feeling of a nightmare operetta, perhaps harking back to █
@pinn0002 you don't need a new pull request. Close the other one. You can just fetch the ones from upstream. Then, re-request a review so I can merge your changes.

2022-05-08 06:21 UTC, cegme commented
A different pull request was merged. Reopen if necessary

2022-05-08 06:21 UTC, closed without merging